version: '3'
services:
  app-server:
    container_name: app
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always
    networks:
      - backend
networks:
  backend:
    driver: bridge
